"""
Takes for Blender Wiki — Jinja macros (mkdocs-macros-plugin).

Loads the UI manifest from `docs/_data/ui_manifest.json` (regenerated by the
deploy workflow before each build) and exposes lookup macros so markdown can
reference live addon values:

    Click the {{ panel('TKS_PT_Navigation').bl_label }} panel.
    Press {{ hotkey('tks.global_delete').key }} to delete.
    {{ op('tks.global_rename').bl_description }}

Lookups raise a `MacroError` when an identifier isn't in the manifest, which
makes drift a hard build failure.
"""

import json
from pathlib import Path

MANIFEST_PATH = Path("docs/_data/ui_manifest.json")


def define_env(env):
    """Entry point called by mkdocs-macros-plugin."""

    if MANIFEST_PATH.is_file():
        manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    else:
        # Local `mkdocs serve` without a fetched manifest: fail fast with a
        # readable error instead of every macro raising.
        manifest = {"_error": f"manifest not found at {MANIFEST_PATH}"}

    env.variables["manifest"] = manifest

    # Build lookup tables once
    by_op_id = {o["bl_idname"]: o for o in manifest.get("operators", [])}
    by_panel_id = {p["bl_idname"]: p for p in manifest.get("panels", [])}
    by_menu_id = {m["bl_idname"]: m for m in manifest.get("menus", [])}
    by_pref_name = {p["name"]: p for p in manifest.get("preferences", [])}
    by_op_keymap = {}
    for k in manifest.get("keymaps", []):
        # First binding for an operator wins; rare to have multiple, fine.
        by_op_keymap.setdefault(k["operator_id"], k)

    def _missing(kind, key):
        if "_error" in manifest:
            return manifest["_error"]
        raise KeyError(
            f"manifest lookup failed: {kind} '{key}' not found. "
            f"This usually means the addon source has changed and the wiki "
            f"page references a stale identifier. Update the markdown."
        )

    @env.macro
    def op(idname):
        """Return the manifest entry for an operator."""
        rec = by_op_id.get(idname)
        if rec is None:
            return _missing("operator", idname)
        return rec

    @env.macro
    def panel(idname):
        """Return the manifest entry for a panel."""
        rec = by_panel_id.get(idname)
        if rec is None:
            return _missing("panel", idname)
        return rec

    @env.macro
    def menu(idname):
        """Return the manifest entry for a menu."""
        rec = by_menu_id.get(idname)
        if rec is None:
            return _missing("menu", idname)
        return rec

    @env.macro
    def pref(name):
        """Return the manifest entry for an addon preference (by attribute name)."""
        rec = by_pref_name.get(name)
        if rec is None:
            return _missing("preference", name)
        return rec

    @env.macro
    def hotkey(operator_id):
        """Return the keymap binding for an operator."""
        rec = by_op_keymap.get(operator_id)
        if rec is None:
            return _missing("hotkey for operator", operator_id)
        return rec

    @env.macro
    def hotkey_str(operator_id, separator="+"):
        """Return a wiki-style keypress string for the first keymap binding
        of an operator, e.g. "ctrl+shift+c"."""
        rec = by_op_keymap.get(operator_id)
        if rec is None:
            return _missing("hotkey for operator", operator_id)
        order = {"ctrl": 0, "shift": 1, "alt": 2, "oskey": 3}
        mods = sorted(rec.get("modifiers", []), key=lambda m: order.get(m, 9))
        return separator.join(mods + [rec["key"].lower()])

    @env.macro
    def keys(operator_id, separator=" / "):
        """Return ALL keypress bindings for an operator as Material kbd
        markup, e.g. '++del++ / ++x++'. Handles operators with multiple
        bindings (alt-binds, accessibility duplicates) gracefully."""
        order = {"ctrl": 0, "shift": 1, "alt": 2, "oskey": 3}
        matches = [k for k in manifest.get("keymaps", [])
                   if k["operator_id"] == operator_id]
        if not matches:
            return _missing("keys for operator", operator_id)
        parts = []
        seen = set()
        for k in matches:
            mods = sorted(k.get("modifiers", []), key=lambda m: order.get(m, 9))
            chord = "+".join(mods + [k["key"].lower()])
            if chord in seen:
                continue
            seen.add(chord)
            parts.append(f"++{chord}++")
        return separator.join(parts)

    @env.macro
    def addon():
        """Shorthand for the addon-metadata block."""
        return manifest.get("addon", {})
