"""Give the menu's SECTION rows an icon, the way page rows already have one.

Page entries carry `icon:` in their front matter, so Material renders an inline
SVG in the drawer. Sections have no page of their own -- they render as a
`<label>`, and front matter has nowhere to live -- so once the four landing
pages were removed, every group row in the menu lost its icon while the page
rows kept theirs.

This writes the missing icons in as a small data file plus an injector. The
paths are lifted from Material's OWN bundled icon set rather than pasted in, so
they stay in step with the theme and are verified to exist at generate time.

Usage:  python dev/gen_nav_icons.py
Re-run after adding a nav section, or after a theme upgrade.
"""

from __future__ import annotations

import importlib.util
import json
import re
from pathlib import Path

WIKI = Path(__file__).resolve().parent.parent
OUT = WIKI / "docs" / "javascripts" / "nav-icons.js"

# Nav row title -> Material icon name. Titles must match mkdocs.yml exactly; the
# injector matches on the row's visible text.
SECTIONS = {
    # Top level -- these repeat the home page's cards on purpose, so the menu
    # and the landing page name the same places the same way.
    "Start Here": "rocket-launch",
    "Guides": "play-circle",
    "How It Works": "lightbulb-on",
    "Inside Takes": "view-dashboard",
    "What's New": "star-shooting",
    # Guides
    "Working with Takes": "movie-open-outline",
    "Looks & Variants": "palette-swatch",
    "Rendering": "image-multiple",
    "Getting Around": "map-marker-path",
    # Inside Takes
    "Panels": "view-dashboard-outline",
    "Features": "shape",
    "Preferences": "cog",
    # Inside Takes > Features
    "Setting Up Looks": "palette-outline",
    "Naming & Output": "rename-box",
    "Working Faster": "speedometer",
    "Modes & Safety": "shield-check",
    "Advanced": "flask",
    # Generated pages -- written by the mirror scripts, so there is no hand
    # front matter to put an `icon:` in. Named here for the same reason
    # sections are.
    "Changelog": "history",
    "Changelog (Dev)": "wrench",
    "Roadmap": "sign-direction",
}

TEMPLATE = r"""/* GENERATED by dev/gen_nav_icons.py -- do not edit by hand.

   Section rows in the menu are <label> elements, not links, so they have no
   front matter to carry an `icon:`. This puts one in front of the row text, in
   the same position and markup Material uses for page rows.

   Scoped to the primary nav: the contents popover clones the page's own table
   of contents, and a heading that happened to read "Advanced" or "Rendering"
   would otherwise grow a section icon.

   Re-runs on every SPA navigation and is idempotent -- a row that already has
   an icon is left alone.
*/
(function () {
  "use strict";

  var ICONS = __ICONS__;

  function decorate() {
    var rows = document.querySelectorAll(".md-nav--primary .md-nav__link");
    Array.prototype.forEach.call(rows, function (row) {
      if (row.closest(".md-nav--secondary")) return;
      if (row.querySelector(":scope > svg")) return;
      var label = row.querySelector(".md-ellipsis");
      if (!label) return;
      var svg = ICONS[label.textContent.trim()];
      if (!svg) return;
      var holder = document.createElement("span");
      holder.innerHTML = svg;
      var node = holder.firstElementChild;
      if (node) row.insertBefore(node, label);
    });
  }

  if (window.document$ && typeof window.document$.subscribe === "function") {
    window.document$.subscribe(decorate);
  } else {
    document.addEventListener("DOMContentLoaded", decorate);
  }
})();
"""


def icon_dir() -> Path:
    spec = importlib.util.find_spec("material")
    if not spec or not spec.submodule_search_locations:
        raise SystemExit("mkdocs-material is not importable")
    d = Path(spec.submodule_search_locations[0]) / "templates" / ".icons" / "material"
    if not d.is_dir():
        raise SystemExit(f"icon set not found at {d}")
    return d


def main() -> int:
    d = icon_dir()
    icons, missing = {}, []
    for title, name in SECTIONS.items():
        f = d / f"{name}.svg"
        if not f.exists():
            missing.append(name)
            continue
        icons[title] = re.sub(r"\s+", " ", f.read_text(encoding="utf-8")).strip()
    if missing:
        raise SystemExit("icons not in this theme version: " + ", ".join(missing))

    data = json.dumps(icons, indent=2, ensure_ascii=False)
    OUT.write_text(TEMPLATE.replace("__ICONS__", data), encoding="utf-8")
    print(f"wrote {OUT.relative_to(WIKI)} with {len(icons)} nav icons")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
