"""Re-use Material's own mobile drawer nav at desktop widths.

Focus mode replaces the permanent desktop sidebar with the slide-in drawer.
The drawer markup is the same at every width, but its *styling* is not:
Material scopes the drawer's nav rules to a mobile media query, so on desktop
the panel was positioned like a drawer while its contents were still styled
like the old fixed sidebar.

Hand-writing a lookalike would drift the moment the theme updates. This lifts
Material's actual rules out of its compiled stylesheet and re-emits them under
the desktop query instead, so the drawer is the theme's own component rather
than an imitation of it.

Writes between markers in docs/stylesheets/extra.css, so re-running replaces the
previous port rather than stacking copies. Re-run after a theme upgrade.

Usage:  python dev/port_mobile_nav.py [--dry-run]
"""

from __future__ import annotations

import glob
import re
import sys
from pathlib import Path

WIKI = Path(__file__).resolve().parent.parent
EXTRA = WIKI / "docs" / "stylesheets" / "extra.css"

MOBILE_Q = "@media screen and (max-width:76.234375em)"
DESKTOP_Q = "@media screen and (min-width: 76.25em)"
BEGIN = "/* >>> PORTED MOBILE DRAWER - generated by dev/port_mobile_nav.py, do not edit <<< */"
END = "/* <<< END PORTED MOBILE DRAWER >>> */"

# Only the drawer's own nav. Pulling every md-nav rule across would also restyle
# the table-of-contents nav, which focus mode clones for its contents popover.
KEEP = re.compile(r"md-nav--primary|md-nav__title|md-nav__source|md-nav__toggle|md-overlay")

# Rules that would fight focus mode's own positioning of the panel.
# ...and never the secondary nav: the contents popover clones it, and the
# drawer's sliding rules would translate that clone off screen.
DROP = re.compile(r"md-sidebar|md-header|md-tabs|md-nav--secondary")


def scope(selector: str) -> str:
    """Confine a rule to the drawer.

    The sliding rules are written generically (`.md-nav__toggle~.md-nav`), so
    applied as-is at desktop they would also catch the table-of-contents nav.
    Prefixing each part with the primary-nav class keeps them where they belong.
    """
    parts = []
    for part in selector.split(","):
        part = part.strip()
        # The overlay is a sibling of the drawer toggle, not part of the nav --
        # prefixing it would stop it matching anything at all.
        if "md-overlay" in part or "md-nav--primary" in part:
            parts.append(part)
        else:
            parts.append(f".md-nav--primary {part}")
    return ", ".join(parts)


def extract_blocks(css: str, query: str):
    """Yield the body of EVERY media block for `query`.

    The theme emits this breakpoint several times over, and the drawer's rules
    are not necessarily in the first one -- reading only that was why an earlier
    pass came back empty.
    """
    found = False
    at = 0
    while True:
        i = css.find(query, at)
        if i < 0:
            break
        found = True
        start = css.index("{", i)
        depth = 0
        for j in range(start, len(css)):
            if css[j] == "{":
                depth += 1
            elif css[j] == "}":
                depth -= 1
                if depth == 0:
                    yield css[start + 1:j]
                    at = j + 1
                    break
        else:
            raise SystemExit("unbalanced braces in stylesheet")
    if not found:
        raise SystemExit(f"media query not found: {query}")


def rules(block: str):
    """Yield (selector, declarations) pairs, skipping nested at-rules."""
    for m in re.finditer(r"([^{}]+)\{([^{}]*)\}", block):
        sel, decl = m.group(1).strip(), m.group(2).strip()
        if sel.startswith("@") or not decl:
            continue
        yield sel, decl


def main() -> int:
    dry = "--dry-run" in sys.argv
    sheets = glob.glob(str(WIKI / "site" / "assets" / "stylesheets" / "main.*.min.css"))
    if not sheets:
        print("ERROR: no built theme stylesheet. Run a build first.")
        return 2

    css = Path(sheets[0]).read_text(encoding="utf-8")
    kept, seen = [], set()
    for block in extract_blocks(css, MOBILE_Q):
        for sel, decl in rules(block):
            if KEEP.search(sel) and not DROP.search(sel) and (sel, decl) not in seen:
                seen.add((sel, decl))
                kept.append((sel, decl))

    if not kept:
        print("ERROR: matched no drawer rules - has the theme's breakpoint moved?")
        return 1

    body = "\n".join(f"  {sel} {{ {decl} }}" for sel, decl in kept)
    ported = (
        f"\n{BEGIN}\n"
        f"/* Material scopes these to {MOBILE_Q}. Focus mode shows the drawer on\n"
        f"   desktop too, so its own rules are replayed here instead of imitated. */\n"
        f"{DESKTOP_Q} {{\n{body}\n}}\n{END}\n"
    )

    text = EXTRA.read_text(encoding="utf-8")
    if BEGIN in text:
        head, rest = text.split(BEGIN, 1)
        text = head + rest.split(END, 1)[1]
    text = text.rstrip() + "\n" + ported

    print(f"{'DRY RUN' if dry else 'WROTE'}: {len(kept)} drawer rules ported")
    for sel, _ in kept[:12]:
        print(f"  {sel[:96]}")
    if len(kept) > 12:
        print(f"  ... and {len(kept) - 12} more")

    if not dry:
        EXTRA.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
