"""
MkDocs hook — keep the "What's New" section out of the site search index.

The changelog and roadmap pages are release logs, not documentation: they
repeat every feature name dozens of times, so a search for any term buries
the actual guide page under a wall of release entries.

Material's search plugin skips a page whose front matter carries
`search: exclude: true` — but the pages under `changelog/` and `roadmap/`
are GENERATED by the deploy workflow (mirrored from the addon repo's
CHANGELOG*.md and built by build_wiki_roadmap.py), so hand-written front
matter would be overwritten on the next build. Setting the meta from a hook
applies to generated and hand-written pages alike.

Excluded pages stay fully browsable via the nav and direct links; they are
only absent from search results.
"""

# Every source path starting with one of these is dropped from the index.
EXCLUDED_PREFIXES = (
    "whats_new/",
    "changelog/",
    "roadmap/",
)


def on_page_markdown(markdown, page, config, files):
    """Stamp `search.exclude` on the excluded pages before they are indexed."""
    if page.file.src_uri.startswith(EXCLUDED_PREFIXES):
        search = page.meta.setdefault("search", {})
        if isinstance(search, dict):
            search["exclude"] = True
    return markdown
